[AND-2530] Mopub mediation settings improvement.
Vungle/mopub-android-mediation pull request #13
Opened 2019-11-27 07:36 UTC by HuFangshuai

We already have the same in VungleMediationSettings.
https://github.com/Vungle/mopub-android-mediation/pull/10/files

2019-11-28 07:20 UTC, HuFangshuai commented on Vungle/src/main/java/com/mopub/mobileads/VungleRewardedVideo.java
> +                MoPubRewardedVideoManager.getGlobalMediationSettings(VungleMediationConfiguration.class);
For api `getGlobalMediationSettings` and `getInstanceMediationSettings` MoPub only handle the two classes which must be of exactly equal types.

2020-01-02 14:43 UTC, alexander-gubov commented on Vungle/src/main/java/com/mopub/mobileads/VungleMediationConfiguration.java
> +        return !localExtras.containsKey(Builder.EXTRA_START_MUTED_KEY) || !localExtras.containsKey(Builder.EXTRA_SOUND_ENABLED_KEY);
Should be "&&"

2020-01-02 14:44 UTC, alexander-gubov requested changes
please check https://github.com/Vungle/mopub-android-mediation/pull/13#discussion_r362496130

2020-01-03 09:46 UTC, alexander-gubov approved these changes
LGTM

2020-01-03 09:48 UTC, alexander-gubov commented
have you changed it back?

2020-01-03 09:51 UTC, HuFangshuai commented on Vungle/src/main/java/com/mopub/mobileads/VungleMediationConfiguration.java
> +        return !localExtras.containsKey(Builder.EXTRA_START_MUTED_KEY) || !localExtras.containsKey(Builder.EXTRA_SOUND_ENABLED_KEY);
fixed.

2020-01-03 09:55 UTC, merged